name = "MyMethods"
uuid = "d4303550-056f-4ba2-a25a-a93f2be184b5"
authors = ["Thomas Wiemann <wiemann@uchicago.edu>"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
